### ISSUE TITLE
Autostart: Missing two strings

### ISSUE THREAD

**Issue by algent-al** [getsolus/budgie-translations#3]
In there Autostart section there are two strings missing to be translated:
"Add application" and "Add command".

![Autostart](https://user-images.githubusercontent.com/46356616/100269026-394d6b00-2f56-11eb-8abf-4c52db3557a8.png)

**Comment by JoshStrobl** [comment]
Not sure why this is being filed in budgie-translations. Budgie Desktop is where the source code is :P

Either way, I'll see about getting that sorted :)

**Comment by algent-al** [comment]
> Not sure why this is being filed in budgie-translations. Budgie Desktop is where the source code is :P

kyrios started first :-P

Thank you for the fix.
